### ISSUE TITLE
 jsctl jac build main.jac will not work at all.

### ISSUE THREAD

**Issue by WrappedUsername** [Jaseci-Labs/jaseci#1072]
**Describe the bug**

I ran this command while following the instructions from [Jaseci docs](https://docs.jaseci.org/docs/docs/getting_started/3_setup_jaseci_serv.html): jsctl jac build main.jac, this command will not work at all, and returns this error:

```bash
2023-04-20 08:01:11,519 - ERROR - interface_error: Internal Exception: [Errno 2] No such file or directory: 'main.jac'
{
  "response": "Internal Exception: [Errno 2] No such file or directory: 'main.jac'",
  "success": false,
  "errors": [
    "Internal Exception: [Errno 2] No such file or directory: 'main.jac'"
  ],
  "stack_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/usr/local/lib/python3.10/dist-packages/jaseci/extens/api/interface.py\", line 192, in general_interface_to_api\n    ret = getattr(_caller, api_name)(**param_map)\n",
    "  File \"/usr/local/lib/python3.10/dist-packages/jaseci/extens/api/jac_api.py\", line 29, in jac_build\n    with open(file, \"r\") as file:\n",
    "FileNotFoundError: [Errno 2] No such file or directory: 'main.jac'\n"
  ]
}
```

**To Reproduce**

- I followed each step in the [docs](https://docs.jaseci.org/docs/docs/getting_started/3_setup_jaseci_serv.html):
![image](https://user-images.githubusercontent.com/104662990/233389069-422f9c40-dde5-4956-a67b-94195ad8bd24.png)

**Expected behavior**

Well I expected it to compile the Jac program to JIR bit. Honestly I only have around a year and a half of experience as a self-taught dev, so I am not sure what else to expect, because if you don't know what to expect, because of a lack of experience and knowledge, how can you know about any other expectations that might be possible?

**Screenshots**

- Started dev server on first terminal:
![image](https://user-images.githubusercontent.com/104662990/233394199-12e95eea-2428-4510-bd56-4548f66b0e09.png)

- Development server started and running on first terminal:
![image](https://user-images.githubusercontent.com/104662990/233388235-74710119-cd86-4e64-b86a-c1b2e6b078eb.png)

- Logged into jaseci shell with new second terminal
![image](https://user-images.githubusercontent.com/104662990/233401907-c5655f1e-fdfe-4345-8412-067fb9f6741c.png)

- I ran jsctl jac build main.jac from my root:
![image](https://user-images.githubusercontent.com/104662990/233391594-3468363b-8a04-4e66-a5cb-0a9c6b10ee55.png)

- Root open in VS Code and I ran the command but nothing happened no errors, eventually I just control+C to escape:
![image](https://user-images.githubusercontent.com/104662990/233389662-b54dd23e-5b76-4437-9fe9-067553543c70.png)

**Environment**
 - OS: [e.g. Linux, WSL]: I have both Ubuntu and WSL2 running on bare metal Kali-Linux
 - Jaseci version: [e.g. 1.0, 1.3, latest main]: I am not sure how to find my jaseci version, but I downloaded last night.
    - I ran:
```bash
root@Arrakis:~# jsctl --version
Usage: jsctl [OPTIONS] COMMAND [ARGS]...
Try 'jsctl --help' for help.

Error: No such option: --version
```

 - kubernetes engine [e.g. docker-desktop, minikub, aws eks]: I have none of these.

**Additional context**

**Comment by WrappedUsername** [comment]
### I am sorry if I did anything wrong with my issue submission, but I forgot to add my screenshot of my localhost:8000
![image](https://user-images.githubusercontent.com/104662990/233404728-82c7efae-3efe-4fa6-8744-f1daf00ba3e7.png)

**Comment by WrappedUsername** [comment]
Also my name is Keefe, and I look forward to building with Jaseci!

**Comment by ypkang** [comment]
Hi Keefe @WrappedUsername Thanks for your interest in Jaseci and for opening up this issue.

As for the issue, this is not your problem at all. The documentation is assuming that you already have a jac application on hand and you are trying to run it (i.e. the `main.jac` mentioned in the docs). So this is a gap in our documentation.

We are in the process of actively revamping our documentation and a good starter journey is one of the places we are working on.

For now, I recommend these two tutorials to get up and running with jaseci
1. [Quickstart (hello world)](https://docs.jaseci.org/docs/docs/examples_and_tutorials/quickstart/quickstart.html)
2. [Building a conversational AI (More advanced)] (https://docs.jaseci.org/docs/docs/examples_and_tutorials/CanoniCAI/CCAI_codelab.html)

**Comment by WrappedUsername** [comment]
Awesome thank you so much for the quick reply! 
I am so excited to learn JAC and Jaseci! 
I did see that the docs on GitHub are still being worked on, and that I can work locally as I learn and develop. 
I am closing this issue because I feel that this issue regarding the docs will be solved soon.
Also a heads up I sent a message on the website about Lecture 3 video on YouTube the audio is really unintelligible (cuts in and out).
I am looking forward to seeing that video with the audio fixed!
These lectures are amazing, please tell everyone involved thank you so much!!!!! 
:rocket:
