### ISSUE TITLE
Jac Cloud Simple Interface to Purge User DB

### ISSUE THREAD

**Issue by ChrisIsKing** [Jaseci-Labs/jaseci#1259]
When developing with jac-cloud, over time you may make several changes to the graph of your application. Examples of changes include adding and updating nodes, adding and updating edge relationships, deleting nodes etc. When you make these changes, existing logic may break and you want to start fresh. I'm thinking we can provide three interfaces to purge the graph of a user.

1. Command Line Interface (CLI) - `jac serve purge --token <token>`
2. REST API - `POST walkers/purge` can be a default `walker` that purges the graph of the user calling.
3. Programmatically in jac - `jac.purge()` or something like that.

**Comment by ypkang** [comment]
Conclusion:
* Let's add the plugin method and jac CLI support. 
* This should be supported in both jaclang and jac-cloud.
