### ISSUE TITLE
[Bug] optional type for walker parameter reduces to None only in jac-cloud APIs

### ISSUE THREAD

**Issue by ypkang** [Jaseci-Labs/jaseci#1263]
## **Describe the bug**
if a walker has a parameter with optional type annotation such as
```
walker example {
    has x: int | None = None;
}
```

When starting with jac-cloud, the endpoint for this walker will require x to be Null only and won't be able to accept actual values

**Comment by amadolid** [comment]
Might need to discuss later as it's working fine on my side

![image](https://github.com/user-attachments/assets/f9204a76-5499-4cd6-a9bf-5d334915e6a5)
![image](https://github.com/user-attachments/assets/479c8916-392c-4971-b781-0aba5bf56ad2)
![image](https://github.com/user-attachments/assets/213d8308-5271-4f8c-99b9-5f731d3a7ae7)

**Comment by ypkang** [comment]
Weird. I can try to reproduce it later.

**Comment by ypkang** [comment]
Yeah it works for me too on latest jac-cloud so this might have been an issue on jaseci 1.0.2. Closing now.
