### ISSUE TITLE
Support for Walker Anchors

### ISSUE THREAD

**Issue by ChrisIsKing** [Jaseci-Labs/jaseci#1295]
In Jac V1, walkers supported a special attribute known as an `anchor` which essentially acted as the return object of that walker when spawned. For e.g

```
walker test_walker {
    has anchor test_anchor: str;

    can set_anchor with `root entry {
        self.test_anchor = "This is a test anchor";
    }

}

with entry {
    response = root spawn test_walker();
    print(response);
}
```
Ideally, in this case, the response object would be mapped to the anchor and the output of print will be the string. Now this can be achieved by having a `has` variable that is not used and set to a default value. However, this tends to clutter the swagger docs and confuses the developer regarding the separation of input parameters from returns.

**Comment by marsninja** [comment]
Hey @ChrisIsKing did we discuss a solution on this one? I remember us discussing it... but cant remember what we decided.

**Comment by marsninja** [comment]
My current thinking is I'm not sure if we need that semantic (can just `print(response.test_anchor)`, would love a compelling case/example.

**Comment by ChrisIsKing** [comment]
@marsninja We discussed it briefly about potentially doing it with `private` attribute but realized that wouldn't work. My main compelling case would be for readability. Anchors allow develops to more cleanly denote the purpose of the walker. While walkers are not exactly functions, most walkers are designed with the purpose of traversing the graph to fetch and information. Even those that are designed solely for invoking abilities and manipulating the graph, one would still want a clearly defined attribute distinguishable from a regular input parameter that denotes success for instance. This is especially true since the idea for jac-cloud is to treat walkers as invokable endpoints.

Here is an example:

```
node data_node {
    has data: dict = {};
}

walker fetch_data {
    has :anchor data: list = []; # Synatax denotes that calling this walker returns a list called data

    can fetch with `root entry {
        visit [-->];
    }

    can grab_data with object entry {
        self.data.append(here);
    }
}

with entry {
    for i in range(10) {
        root ++> data_node(data={'value': i});
    }
    data = root spawn fetch_data();
    print(data);
}
```

Compared to:

```
node data_node {
    has data: dict = {};
}

walker fetch_data {
    has data: list = []; # Synatax denotes that calling this walker returns a list called data

    can fetch with `root entry {
        visit [-->];
    }

    can grab_data with object entry {
        self.data.append(here);
    }
}

with entry {
    for i in range(10) {
        root ++> data_node(data={'value': i});
    }
    data = root spawn fetch_data();
    print(data);
}
```

Code block 1 allows the reader to know that the purpose of invoking/spawning this walker is to fetch and return data.

**Comment by marsninja** [comment]
At the moment, walkers return the state of the walker object after the spawn. Treating the returns of a walker spawn with consistent semantics as producing an object instance of the walker itself may be a bit simpler to understand and interact as opposed to the spawn call return a particular field of the walker. There's perhaps loss of the walker object in the spawn call in your example. 

For instance consider how we'd express the following with anchor

```
node data_node {
    has data: dict = {};
}

walker fetch_data {
    has data: list = [];
    has other_data: list=[]; 

    can fetch with `root entry {
        visit [-->];
    }

    can grab_data with object entry {
        self.data.append(here);
    }
}

with entry {
    for i in range(10) {
        root ++> data_node(data={'value': i});
    }
    data = root spawn fetch_data();
    print(data.data);
    print(data.other_data); #I believe we'd loose the ablity of accessing this in the anchor example 
}
```

What do you think?

**Comment by ChrisIsKing** [comment]
@marsninja Makes sense. Certainly don't think that the convention of having the walker object returned be removed. This is more of my thinking coming from jac v1 where standalone functions weren't present as they are now in `jaclang`. So walkers were used essentially as standalone functions as well. 

What I do think can be confusing to learners is in `jac-cloud` land walkers are viewed as endpoints whereas in pure jaclang they're more of a construct for graph interaction. So depending on where you start from, the shift from one to the next can throw you off.

 This has me thinking that from a pedagogy standpoint, there should be guided recommendations for walker use to prevent the aforementioned confusion. Take this for example:
 
 ```
 node data_node {
    has data: dict = {};
}

walker fetch_data {
    has data: list = []; 

    can fetch with `root entry {
        visit [-->];
    }

    can grab_data with object entry {
        self.data.append(here);
    }

    can return_data -> list {
        return self.data;
    }
}

with entry {
    for i in range(10) {
        root ++> data_node(data={'value': i});
    }
    wlk_obj = fetch_data();
    print(wlk_obj.return_data());
    root spawn wlk_obj;
    print(wlk_obj.return_data());
}
```

In this example, we can see how treating the walker more like a function, especially with a dedicated return method like return_data, makes it easier to access and manipulate walker-specific data consistently across different contexts. This is more Java-like. This pattern not only reduces ambiguity but also highlights the explicit role of the walker in processing graph nodes while retaining its state more predictably. The main thing I'm considering is maintaining the distinction between walkers as graph manipulators and walkers as function-like entities. Here the only thing the developer has to do if switching to API land is add an ability like:

```
can return_data with exit {
        report self.return_data;
}
```

That said, there's a caveat when it comes to the naming of walkers themselves. In non-function use cases, naming walkers in a way that resembles function names (like `fetch_data`) could be confusing, especially when the walker is primarily meant to manipulate graph nodes rather than return a value or perform a single, isolated task.

I'm fine with closing this.

**Comment by marsninja** [comment]
Yes this is a good discussion, throw this on @TharukaCkasthuri's documentation roadmap. Feel free to close this after.
