### ISSUE TITLE
[Bug] Variables Dynamically Added to Walker Do Not Print

### ISSUE THREAD

**Issue by ChrisIsKing** [Jaseci-Labs/jaseci#1296]
When variables are dynamically added to a walker, `print()` does not show it despite being accessible. Consider the following test case:

```
walker test_walker {
    has z: int;

    can set_vars with `root entry {
        self.x = 1;
        self.y = 2;
    }
}

with entry {
    walk_obj = root spawn test_walker(z=3);
    print(walk_obj);
    print(walk_obj.__dict__);
    print(walk_obj.x);
    print(walk_obj.y);
    print(walk_obj.z);
}
```

Upon execution, this results in the following output:
```
test_walker(z=3)
{'__jac__': WalkerAnchor(architype=test_walker(z=3), id=afb57a93-6926-4d41-8398-b04013aa0185, root=None, access=Permission(all=<AccessLevel.NO_ACCESS: -1>, roots=Access(anchors={})), persistent=False, hash=0, path=[], next=[], ignores=[], disengaged=False), 'z': 3, 'x': 1, 'y': 2}
1
2
3
```

**Comment by ChrisIsKing** [comment]
This can in part be solved by the introduction of anchors. See: https://github.com/Jaseci-Labs/jaseci/issues/1295

**Comment by marsninja** [comment]
This is occurring simply by virtue of us using the dataclass semantics for nodes/walkers/edges/objs. Dataclasses in python rewrites the __repr__ to only include the explicitly specified fields. Let me know if there is a compelling example we'd want to be more flexible with monkey patching. Given that Jac aspires to be a strongly typed language monkey patching is discouraged (though it could work notwithstanding the type errors that should be fired by the type checker).

**Comment by ChrisIsKing** [comment]
This is fine. I'm okay with this not being explicitly available. No glaring need to monkey patch since it can still be accessed via `__dict__`.
