### ISSUE TITLE
Combination of Doc Gaps

### ISSUE THREAD

**Issue by Gorgeous-Patrick** [Jaseci-Labs/jaseci#130]
## Wrong parts / misunderstandings
- [ ] Missing minikube start
Location: Getting Started -> Starting Jaseci Services
Description: We need to remind the users to start the minikube services before starting the jaseci system. `minikube start`.
- [ ] How does the type system work?
Location: Your first Jac Program -> Data Models and Walkers -> Adding friends
Description: It seems that the `new_friend` does not have any associated type. How can anyone decide that it is a `person`.
- [ ] Add some more friendly help on AI itself.
Location: Your first Jac Program -> Adding an AI Component
Description: I, as a newbie of AI here, I was so confused about what is embedding. I think this might not be in the scope of this document but it wopuld be nice if we could provide some simplest explanation.
- [ ] JacApi package not found
Location: Your first Jac Program -> Adding an AI Component -> Demo
Description: The tutorial does not specify how to install the API package and it does not tell the user where the API source codes are.

## Things to include
- [ ] About unit test.
- [ ] About `graph` keyword and how to use it.
- [ ] It seems that we have not included an example that tells the user that we can do something like:
```
walker hello{
root, node1, node2{...}
}
```

**Comment by ypkang** [comment]
Sentinel register update needs to be updated as well. 

```
sentinel register -name fam -code fam.jac -set_active true
```

Code is no longer an argument.
