### ISSUE TITLE
[Bug] Extra single quotes added when using triple single-quoted string

### ISSUE THREAD

**Issue by AshishMahendra** [Jaseci-Labs/jaseci#1351]
## **Describe the bug**

When using both triple double quotes (`"""`) and triple single quotes (`'''`) to define strings, the output behaves unexpectedly by including extra single quotes in the printed result for the `single` variable.

### **Expected Behavior**
Both `multi` and `single` should output the string without extra single quotes.

- `multi` = `"""I'm a triple quoted string"""` should output:
  ```
  I'm a triple quoted string
  ```

- `single` = `'''I'm also a triple quoted string'''` should output:
  ```
  I'm also a triple quoted string
  ```

### **Actual Behavior**

The `multi` string is printed correctly, but the `single` string adds extra quotes around the result:

```
I'm a triple quoted string
''I'm also a triple quoted string''
```

### **To Reproduce**

Steps to reproduce the issue:
1. Define a multi-line string using triple double quotes (`"""`) and triple single quotes (`'''`).
2. Print both variables.
3. Observe the output for the `single` string includes extra single quotes.

Example code:
```jac
with entry{
    multi = """I'm a triple quoted string""";
    single = '''I'm a triple quoted string''';
    print(multi);
    print(single);
}
```

### **Environment:**
- **Jac Version:** 0.7.22

**Comment by kugesan1105** [comment]
Fixed 👍 https://github.com/Jaseci-Labs/jaseci/pull/1378
