### ISSUE TITLE
[Bug] Syntax error with custom types in `has` declaration

### ISSUE THREAD

**Issue by musab-mah-7** [Jaseci-Labs/jaseci#1370]
## **Describe the bug**
The declaration `has some: priv T;` results in a syntax error when `T` is a custom type. However, this syntax works without issues for primitive types like `int` or `str`. This inconsistency needs to be addressed.

### **To Reproduce**

1. Create an object with a custom type using the `has` declaration.
2. Attempt to compile or run the code.

#### Expected Outcome:
The syntax should be consistent, allowing custom types in the `has` declaration without errors.

**Comment by kugesan1105** [comment]
## Correct Syntax Example:

obj Shape {
    has :priv shape_type: ShapeType;

    has :protect radius: float,
        area: float;

    has name: str;
}

@musab-mah-7   https://github.com/Jaseci-Labs/jaseci/issues/1405
