### ISSUE TITLE
Add the option of CosineSimilarity loss for bi-encoder training

### ISSUE THREAD

**Issue by StefanHeng** [Jaseci-Labs/jaseci#145]
CosineSimilarity is a commonly used loss in training. I'd like to have that option for training the jskit::BiEncoder, for potentially comparing the results with those described in papers. 

The [existing implementation](https://github.com/Jaseci-Labs/jaseci/blob/main/jskit/encoders/utils/models.py#L227-L230) maximizes the dot product. We just need to add an additional normalization. 

For now, I'll align to the existing implementation by supporting only positive label cases. 

Another note: as linked above, correct me if I'm wrong - looks like we're computing the dot product between *every possible* context-candidate pair and then filtering them with `eye`. This is effectively the same as just computing the dot product between each *corresponding* pair, which is more efficient.

**Comment by ypkang** [comment]
Thanks for contributing @StefanHeng. Looking forward to the PR!
