### ISSUE TITLE
[Bug] Unable to Remove Specific Edge Using `del -:edge_name:->` in Jaclang

### ISSUE THREAD

**Issue by musab-mah-7** [Jaseci-Labs/jaseci#1463]
Currently, in Jaclang, it is possible to remove a generic edge or all edges between two nodes using the` del `operation. For example:

`node_1 del --> node_2;  // This removes all edges between node_1 and node_2.`

However, when attempting to remove a specific edge between two nodes, the operation does not work as expected. For instance, consider the following example:
```

node a {
    has value:int = 10;
}

edge b {
    has value:int = 20;
}

edge c {
    has value:int = 30;
}

with entry {
    node_1 = a(value=5);
    node_2 = a();

    root ++> node_1;
    node_1 +:b(value=5):+> node_2;
    node_1 +:c(value=10):+> node_2;

    node_1 del -:c:-> node_2;  // This should remove only edge 'c'.
}
```

Here, the command `node_1 del -:c:-> node_2`; is expected to remove only the edge of type c between node_1 and node_2. However, this does not work, and the edge remains intact.
###  Expected Behavior:
The command `node_1 del -:c:-> node_2;` should remove only the specific edge of type c between node_1 and node_2 without affecting other edges.
### Actual Behavior:
The command does not remove the specific edge c. Instead, all edges must be deleted using `node_1 del --> node_2;`, which removes all edges between the nodes.

###  Steps to Reproduce:

-     Define nodes and edges as shown in the example above.
-     Add multiple edges of different types between two nodes.
-     Attempt to remove a specific edge using the del -:edge_name:-> syntax.
-     Observe that the specific edge is not removed.

**Comment by ThakeeNathees** [comment]
Closing as it seems to be working from Jaclang and the issue might raise from some other area.
