### ISSUE TITLE
Revamp docs and migrate to docusaurus 

### ISSUE THREAD

**Issue by marsninja** [Jaseci-Labs/jaseci#16]
For the official Jaseci docs we should use docusaurus (https://docusaurus.io/docs/installation) as its become quite the standard. 

Lets draw some inspiration from the wonderful team at Rasa: https://github.com/RasaHQ/rasa/tree/main/docs

Our current docs (https://docs.jaseci.org/) should be easy to translate since its markdown based already. @ypkang has the code in a private repo somewhere. Lets open up this bad boy!!

**Comment by ypkang** [comment]
👍🏼
