### ISSUE TITLE
jaseci_serv as standalone package

### ISSUE THREAD

**Issue by marsninja** [Jaseci-Labs/jaseci#17]
Would be nice to have a standalone for the jaseci server. Something like a 'jsserv' that works much like 'jsctl' but launches the django rest server. Also, that package can then be put into pypi so you can do something like 

```
pip install jaseci_server
jsserv
```

to get up and running. 

Also, this jsserv should auto detect whether there is a postgres on the network, and if not it should just use a local sqlite db, so it would work seamlessly no matter where you run it.

**Comment by marsninja** [comment]
Another cool thing here is once we introduce our setup.py we can get rid of the requirements.txt, so a little more elegant.

**Comment by ypkang** [comment]
Oh I like the local sqlite backup idea! That would make getting a jaseci instance up and running really easy.
