### ISSUE TITLE
JSCTL Shell Script

### ISSUE THREAD

**Issue by Gorgeous-Patrick** [Jaseci-Labs/jaseci#204]
**Is your feature request related to a problem? Please describe.**
I think that JSCTL is a shell. Do we have a way to write JSCTL shell scripts in a file and then run that file with probably shebang? It seems that sometimes people have to run sentinel register and multiple walkers to see the effect of their changes in code. It might be helpful if we could just store all the JSCTL command needed in a script file and then run it every time.

**If this feature request is accepted, would you be willing to work on a PR?**
Yes/No: Sure

**Comment by marsninja** [comment]
This idea is a very good one. Would love to hop on an implementation brainstorm / code surfing call with you. For now, do note that there is the `jsctl -m jac run file.jac` type calls that will let you compile and run jac programs directly from command line. There's also `jsctl -m jac test file.jac` that will run tests.

**Comment by Gorgeous-Patrick** [comment]
> This idea is a very good one. Would love to hop on an implementation brainstorm / code surfing call with you. For now, do note that there is the `jsctl -m jac run file.jac` type calls that will let you compile and run jac programs directly from command line. There's also `jsctl -m jac test file.jac` that will run tests.

I have several walkers in one file. I need to run createPredefine first and then run the walker segmenter. Probably in the future, the walkers will require parameters. Is this possible with `jac run`?

**Comment by ypkang** [comment]
This is supported now.
