### ISSUE TITLE
Bi-encoder and js-segmenter returning errors for no reason

### ISSUE THREAD

**Issue by Gorgeous-Patrick** [Jaseci-Labs/jaseci#269]
**Describe the bug**
Biencoder and flair just return errors for no reason.

**To Reproduce**
Please setup jaseci server and Biencoder in kubernetes. Load the biencoder remotely.
And try to upload the following program:
```
walker init {
    can bi_enc.infer;
    root {
        report bi_enc.infer(contexts = "I like the restaurant near my house!", candidates = ["University", "restaurant", "school", "computer"]);
    }
}
```
Using the locust load test program, I find that the system returns 
```json
{"success":true,"report":[{"detail":[{"loc":["body","contexts"],"msg":"value is not a valid list","type":"type_error.list"},{"loc":["body","contexts"],"msg":"value is not a valid list","type":"type_error.list"},{"loc":["body","context_type"],"msg":"none is not an allowed value","type":"type_error.none.not_allowed"},{"loc":["body","candidate_type"],"msg":"none is not an allowed value","type":"type_error.none.not_allowed"}]}]}
```
The program succeeded meaning that it might not be the bug of the load test part, but the biencoder always returns none.

When I use `kubectl logs BIENCODER_PODNAME`, I find
```
INFO:     172.17.0.1:26724 - "POST /infer HTTP/1.1" 307 Temporary Redirect
INFO:     172.17.0.1:26724 - "POST /infer/ HTTP/1.1" 422 Unprocessable Entity
```
I believe that similar issues happen with text segmenter. But I am not exactly sure.
**Expected behavior**
I believe that it should just give me a string in the report (maybe restaurant).

**Screenshots**

**Environment**
 - OS: [e.g. Linux, WSL] Manjaro Arch Linux
 - Jaseci version: [e.g. 1.0, 1.3, latest main] Lastest main
 - kubernetes engine [e.g. docker-desktop, minikub, aws eks] minikube

**Additional context**

**Comment by ypkang** [comment]
Hi @Gorgeous-Patrick thanks for reporting this issue. The biencoder actually expects the following input format
```
{
  "contexts": [
    "string"
  ],
  "candidates": [
    "string"
  ],
  "context_type": "text",
  "candidate_type": "text"
}
```
Can you try updating your code accordingly and try again? Sorry about the confusion -- we are actively improving the documentation around jaseci kit :)

**Comment by Gorgeous-Patrick** [comment]
> Hi @Gorgeous-Patrick thanks for reporting this issue. The biencoder actually expects the following input format
> 
> ```
> {
>   "contexts": [
>     "string"
>   ],
>   "candidates": [
>     "string"
>   ],
>   "context_type": "text",
>   "candidate_type": "text"
> }
> ```
> 
> Can you try updating your code accordingly and try again? Sorry about the confusion -- we are actively improving the documentation around jaseci kit :)

No the same problem remains. It seems that the function requires a Union instead of a single string? The original function declaration is listed here:
```python
@jaseci_action(act_group=["bi_enc"], allow_remote=True)
def infer(
    contexts: Union[List[str], List[List]],
    candidates: Union[List[str], List[List]],
    context_type: str,
    candidate_type: str,
):
```

**Comment by Gorgeous-Patrick** [comment]
Fixed
