### ISSUE TITLE
Error Handling on walker spawns

### ISSUE THREAD

**Issue by asimsalim** [Jaseci-Labs/jaseci#30]
Currently with nested walkers even one spawn failing results in the whole operation failing. 
It would be great to have a try spawn walker .... else or even a general try ... else feature in jac for better error handling functionality.

**Comment by marsninja** [comment]
This is a brilliant observation Asim, is this an annoying pain point at the moment? I can certainly prioritize addressing this. I have couple elegant semantics I can knock out. 

try - spawn - else
try {} else
with a raise keyword and an exception keyword that references whatever was raised on exception, 

Let me know if you want it now @asimsalim, (totally ok to say yes, i will enjoy hacking this out immensely}

**Comment by asimsalim** [comment]
@marsninja  This is not an immediate priority. Rather a good to have feature.
