### ISSUE TITLE
Forshadowing issues with eager delete write through, and lazy update write-back approach for walker/request transaction handeling

### ISSUE THREAD

**Issue by marsninja** [Jaseci-Labs/jaseci#34]
Was daydreaming and find that there is a possibility of incoherent state with the eager write through on delete operations for object and lazy updates.

Solution would be to mark objects as deleted in the mem_hook implementation and have lazy write back for object deletes alongside object updates. With that the stack would see the not-yet-committed transactional state during a walk and if something goes wrong, the persistent state is as if the walk never occurred. This is all relevant to derivatives to mem_hook such as orm_hook.

**Comment by ypkang** [comment]
@marsninja still valid issue?
