### ISSUE TITLE
A couple tests are  are too over specified and not nimble

### ISSUE THREAD

**Issue by marsninja** [Jaseci-Labs/jaseci#371]
Hey @amadolid , A couple of the tests with your PRs are a little over specified and we should improve. 

In particular, I'm adding features to the dictionary returned after walker runs and every addition breaks all of your tests. 

An example of what I mean is instead of having an assert in the test look like: 

```
default_res = {"success": True, "report": [True, True, default_file]}
self.assertEquals(res, default_res)
```

I'd rewrite to be

```
self.assertTrue(res["success"])
self.assertEqual(res["report"][2], default_file)
....
```

For big result payloads like in test_global_ref I'd just check the specfic items in teh payload you'd want to validate rather than an entire payload equality check. 

Problematic tests include: 
test_global_ref
test_multipart_custom_payload_with_additional_file
test_multipart_custom_payload_with_additional_file
test_multipart_json_file
test_multipart_json_string
test_multipart_with_additional_file

**Comment by ypkang** [comment]
@amadolid have tests been updated or they still need to?
