### ISSUE TITLE
Revise the organization of Jaseci documentation within the Codebase

### ISSUE THREAD

**Issue by eldonm** [Jaseci-Labs/jaseci#395]
The basis of this proposed revision  is capitalizing on the markdown table of contents while ensuring that every major aspect of Jaseci has its own README.md. The main README.md should be the master TOC for the Jaseci docs with references that map to Jaseci Kit, Jaseci Core, etc. When devs work on and update their respective modules, for example, they author their own README.md for that module and ensure that the library's TOC and the master TOC are updated with the entry as well (usually this only has to be done once). Each major area within the Jaseci library (such as jaseci_kit) should contain a description/overview as well as a TOC list of related sub items. All other content not directly related to functional modules within Jaseci's libraries will be stored in /support/guide,.. such as installation, JAC Programming Guide. Ultimately, the entirety of Jaseci docs will be part of the repo (not as a separate distro as in the case of docusaurus) and this should permit us to capitalize on PRs to collectively update the docs as well as allow devs to browse the docs directly from the repo. We could still maintain docusaurus but the repo's docs will be its source. Finally, we can use a tool like mdBook which can automatically generate a browsable compilation of the docs, even with Jekyll syntax highlighting and other bells and whistles.  I've included screenshots and a demo setup here: https://github.com/eldonm/jaseci-repo-shell

**Comment by ypkang** [comment]
This has been accomplished with the mdbooks revamp of documentation.
