### ISSUE TITLE
Contributor License Agreement?

### ISSUE THREAD

**Issue by ypkang** [Jaseci-Labs/jaseci#48]
Rasa has a License Agreement for contributor to be able to merge code. Do we need something like this?

https://cla-assistant.io/RasaHQ/rasa

**Comment by marsninja** [comment]
After reading: https://opensource.google/docs/cla/  I think its important we have it in place. See if you can come up with a quick dgital way folks can do it. We can use the rasa approach if its easy.

**Comment by marsninja** [comment]
Oh I see rasa has a sign with github, thats perfect! Lets do it! @ypkang

**Comment by marsninja** [comment]
@ypkang We should knock this out when we get a chance.

**Comment by ypkang** [comment]
CLA integration is in place now.

For new PRs from now no, github will check if all the authors have signed the CLA and comment on the PR with how to sign if needed. After all authors have signed, this badge will be on the PR:

![image](https://user-images.githubusercontent.com/3213561/150192645-a8a60d99-f5f6-4d9a-ab8b-02f8235cc3c3.png)

and a green checkmark on the PR.

Here is the CLA. https://gist.github.com/ypkang/493613f9b0d2b4cab0f15741784f5e77
