### ISSUE TITLE
Firebase Integration for Jaseci

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaseci#504]
**Describe the solution you'd like**
The ability to use firebase would be a game changer for jaseci because currently most of the developers are used to creating apps with firebase and if they are thinking of moving to jaseci, this would be a huge encourager.

**If this feature request is accepted, would you be willing to work on a PR?**
Yes

**Comment by ypkang** [comment]
@chandralegend Could you elaborate more on the idea? How would Firebase and Jaseci be utilized together?
