### ISSUE TITLE
Would be great to have some zlib functions in the standard library

### ISSUE THREAD

**Issue by marsninja** [Jaseci-Labs/jaseci#583]
**Is your feature request related to a problem? Please describe.**
It would be very useful if Jaseci had some gzip compatible standard library functions. 

**Describe the solution you'd like**
It would be helpful if there were some actions like `zlib.compress` and `zlib.decompress` that can be used in the Jac programming language. To adhere to Jac's principles these functions should take in base64 strings as input and produce base64 as output. I'd think a good design would be to convert the base64 input into bytes, perform compression, then encode the compressed bytes into base64 again for the return. 

**If this feature request is accepted, would you be willing to work on a PR?**
If time allows.

**Additional context**
I'd imagine this library would piggyback on pythons zlib functions.

**Comment by apatel66** [comment]
Hi, Matthew Wang (@Hextechagon) and I are juniors at the University of Michigan taking a software development class. Our latest assignment is to contribute to an open source project. We would like to contribute to Jaseci so would you be able to assign this issue to Matthew and I? Thanks!

**Comment by marsninja** [comment]
Sure thing!

**Comment by marsninja** [comment]
@Hextechagon reply to this thread if you can. I'm trying to get github to let me assign you but I suspect you have to comment first.

**Comment by Hextechagon** [comment]
Hi, sure thing!

**Comment by Hextechagon** [comment]
Hi @marsninja , can you assign this issue to me too? Thanks!

**Comment by ypkang** [comment]
@Hextechagon assigned it to you. How is this coming along? Feel free to reach out to me or @marsninja if you need anything.

**Comment by Hextechagon** [comment]
Thanks, we're making progress.
