### ISSUE TITLE
Github actions for CI/CD

### ISSUE THREAD

**Issue by ypkang** [Jaseci-Labs/jaseci#60]
Should have the jaseci tests as part of github actions, run against every PR and master branch automatically.

**Comment by ypkang** [comment]
* CI pipeline
  * This runs on each PR.
  * Can’t merge unless this passes.
  * This should run on main after each commit to main
  * This includes:
    * Jaseci-core unit tests
    * Jaseci-serv unit tests
    * Linting
    * Sonar quality/health check

* CD pipeline
  * This can be triggered manually by making a release tag in github
  * This includes
    * First validate with the CI tests
    * Update jaseci on pypi
    * Update jaseci_serve on pypi
    * Update ai-ready docker images on dockerhub

**Comment by ashagraw91** [comment]
70% done

**Comment by ypkang** [comment]
This is almost all done. The only remaining item is CD to dockerhub, which have another issue for.
