### ISSUE TITLE
Elastic Logging

### ISSUE THREAD

**Issue by amadolid** [Jaseci-Labs/jaseci#639]
**Is your feature request related to a problem? Please describe.**
This is not a problem I think since some of it can be handle in Jac. Tho having elastic logging as a built in functionality might be good in some implementation. For example:
- we can structurize current logger and save it to elastic so that we can backtrack issues easier or with pattern
- we can implement activity logs. For example we can flag a walker that's needed to be logged every entry

**Describe the solution you'd like**
We can implement service for elastic (similar to male). Credentials will be set on service's config. This service will be use as action like `elastic.log(arg1, arg2);` (similar to `mail.send`).

**Describe alternatives you've considered**
Adding request post for creating elastic log or replacing util's logger to elastic (if enabled) will work too

**If this feature request is accepted, would you be willing to work on a PR?**
Absolutely and a cheerful yes!

**Additional context**
Currently, we can use global vars for credentials and use it for request.post in elastic endpoint. This requires dedicated walker just for reconstructing again the request post

**Comment by ypkang** [comment]
Closed with #757
