### ISSUE TITLE
Avoid potential OOM issue with logging api

### ISSUE THREAD

**Issue by marsninja** [Jaseci-Labs/jaseci#645]
Current logging api to get logs uses a string buffer that continuously grows. We should create a limited sliding buffer. This link has a partial solution https://bytes.com/topic/python/answers/169145-feature-request-max-size-limit-stringio

I'd replace `raise IOError("allocated buffer space exceeded")` with logic to chop of the the difference between `cursize` and `maxsize` and then reset `cursize` to `maxsize`, then `write of course`

**Comment by ypkang** [comment]
@Gim3l is this resolved or still needs to be done?
