### ISSUE TITLE
Ability to parse parameters to an action module

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaseci#670]
Currently, when we load a module through `actions load module jaseci_ai_kit.bart_sum`, the initialization only happens for the `bart-large-cnn` model. 

What If we can parameterize the model initialization, where we can say which model to use. then the JAC user has the ability to change the module on the load stage.

Example Behavior for JSCTL
```bash
jac> actions load module jaseci_ai_kit.bart_sum --ctx {"model":"bart-tiny-cnn"}
```

Example change in Jaseci AI Kit code
```python
def setup(model):
  bart_tokenizer = BartTokenizer.from_pretrained(f"facebook/{model}")
  bart_model = BartForConditionalGeneration.from_pretrained(f"facebook/{model}").to(
      device
  )

setup(model)
```

**Comment by ypkang** [comment]
Duplicate with #730
