### ISSUE TITLE
New Jaseci AI Kit Organization

### ISSUE THREAD

**Issue by ypkang** [Jaseci-Labs/jaseci#743]
![jaseci ai kit re-org proposal](https://user-images.githubusercontent.com/3213561/211418704-1a1f674b-b992-4b1b-b69a-3fb6f2be6c6b.png)

**Comment by ypkang** [comment]
Okay great. I will plan out the transition plan for this. Shouldn't take long if @chandralegend and/or @AshishMahendra help me here.

**Comment by ypkang** [comment]
Todos:
- [x] Create new folder structure
- [x] Set up pypi scaffolding for each folder
- [ ] Move each module to the correct folder location
  - [ ] This includes adding the package dependencies to the relevant setup.py
- [ ] Update github test pipeline
- [ ] Update github package build/deploy pipeline

**Comment by ypkang** [comment]
Todos:
- [x] Create new folder structure
- [x] Set up pypi scaffolding for each folder
- [ ] Move each module to the correct folder location
  - [ ] This includes adding the package dependencies to the relevant setup.py
- [ ] Update github test pipeline
- [ ] Update github package build/deploy pipeline

**Comment by chandralegend** [comment]
https://github.com/Jaseci-Labs/jaseci/pull/765

**Comment by chandralegend** [comment]
![screenshot_2023-01-13_at_20 41 20](https://user-images.githubusercontent.com/52673571/213003155-292663c1-f501-42cf-8a45-f17311e71159.png)

**Comment by chandralegend** [comment]
- [X] Move each module to the correct folder location
    - [X]  This includes adding the package dependencies to the relevant setup.py
- [X]  Update github test pipeline

**Comment by ypkang** [comment]
Closed with #765 #784
