### ISSUE TITLE
Identify approach to move jaseci ai kit dependencies into individual actions

### ISSUE THREAD

**Issue by ypkang** [Jaseci-Labs/jaseci#749]

**Comment by ypkang** [comment]
@chandralegend can you attach your diagram here?

**Comment by chandralegend** [comment]
![screenshot_2023-01-13_at_20 41 20](https://user-images.githubusercontent.com/52673571/213003508-efdcbb4c-c5a5-4971-a9d8-c858beddb289.png)

**Comment by ypkang** [comment]
Closed with #765
