### ISSUE TITLE
Create requirements.darwin.txt for all jaseci ai kit modules and update setup.py to work with platform-dependent packages

### ISSUE THREAD

**Issue by ypkang** [Jaseci-Labs/jaseci#801]

**Comment by ypkang** [comment]
@chandralegend Add your diagram here please.

**Comment by chandralegend** [comment]
<img width="1020" alt="Screenshot 2023-01-26 at 17 17 58" src="https://user-images.githubusercontent.com/52673571/214828055-25839ef2-8342-4de2-a196-6da9cef3e684.png">
