### ISSUE TITLE
Extract topics from a single statement 

### ISSUE THREAD

**Issue by timothy-shiwprasad** [Jaseci-Labs/jaseci#830]
#Using the topic extraction module I would like to extract the topics from a single statement . for instance if I enter the statement [I like dogs ] , the topics extracted would be [dog ,like].  @TharukaCkasthuri

**Comment by TharukaCkasthuri** [comment]
@ypkang is this basically keyword extraction?

**Comment by TharukaCkasthuri** [comment]
Closing as completed in #837
